  name: Test debug

  on:
    workflow_call:

  jobs:
    test:
      name: Testing debug variant
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Setup Gradle
          uses: gradle/actions/setup-gradle@v4

        - name: Make gradlew executable
          run: chmod +x ./gradlew

        - name: Execute gradle command - testDebugUnitTest
          run: ./gradlew testDebugUnitTest