name: On Pull Request Opened

on:
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    name: Lint debug
    uses: ./.github/workflows/job_lint_debug.yml

  test:
    name: Test debug
    needs: lint
    uses: ./.github/workflows/job_test_debug.yml